# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: luberlu
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: tests
# "service" is the name of this project. This will also be added to your AWS resource names.
service: express-nosql-serverless

frameworkVersion: '4.2.3'

plugins:
  - serverless-dynamodb
  - serverless-offline

custom:
  serverless-dynamodb:
    stages:
      - dev
    start:
      port: 8001
      inMemory: true
      docker: false
      migrate: true
      seed: true
    seed:
      test:
        sources:
          - table: "users-table-dev"
            rawsources: [./data-json/fake-test-users.json]

stages:
  default:
    params:
      tableName: "users-table-${sls:stage}"

provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [UsersTable, Arn]
  environment:
    USERS_TABLE: ${param:tableName}

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"
  helloWorld:
    handler: handler.helloWorld
    events:
      - httpApi: "GET /hello"

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:tableName}
